spring:
  cloud:
    nacos:
      discovery:
        cluster-name: HZ
        namespace: e880a951-e449-48f6-84d5-f3098e5ffb57
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
server:
  port: 10010

