server:
  port: 10011
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AddRequestHeader= a,c # 局部过滤器
      default-filters: # 默认全局过滤器
        - AddRequestHeader=a,b
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题（第一次ajax要询问，需要发送options请求）
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8090"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*" # 允许请求头的任何信息
            allowedCredentials: true #是否允许Cookie
            maxAge: 300000 #跨域检测有效期
  application:
    name: eureka-gateway-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka