server:
  port: 8083
spring:
  application:
    name: order-service
eureka:
  client:
    service-url:
      default-url: http://localhost:8761/eureka
logging:
  level:
    com:
      example:
        orderservicedemo: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单路劲最大连接数
  client:
    config:
      default:
        loggerLevel: FULL # 日志等级
