server:
  port: 8083
spring:
  application:
    name: order-service
eureka:
  client:
    service-url:
      default-url: http://localhost:8761/eureka
logging:
  level:
    controller: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

