server:
  port: 8081
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    userservicedemo: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
